# API PULL RICK AND MORTY CHARACTHER

In [1]:
import requests
url = "https://rickandmortyapi.com/api/character/108"

In [2]:
import time
import pandas as pd
import requests

In [3]:
name = []
species = []
status = []
count = 0
for i in range(1,11):
    url = f"https://rickandmortyapi.com/api/character/{i}"
    resp = requests.get(url)
    result  = resp.json()
    name.append(result['name'])
    species.append(result['species'])
    status.append(result['status'])
    time.sleep(1) #seconds
    count += 1
    print(count)
#url = "https://swapi.dev/api/people/"
df = pd.DataFrame({
    "name":name,"species":species,"status":status
})
df

1
2
3
4
5
6
7
8
9
10

                        name species   status
0               Rick Sanchez   Human    Alive
1                Morty Smith   Human    Alive
2               Summer Smith   Human    Alive
3                 Beth Smith   Human    Alive
4                Jerry Smith   Human    Alive
5  Abadango Cluster Princess   Alien    Alive
6           Abradolf Lincler   Human  unknown
7           Adjudicator Rick   Human     Dead
8            Agency Director   Human     Dead
9                 Alan Rails   Human     Dead

# SKLEARN BASICS

In [55]:
!pip3 install -U scikit-learn scipy matplotlib

Collecting scikit-learn
  Downloading scikit_learn-1.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 1.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (1.8.0)
Collecting scipy
  Downloading scipy-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 587.5 kB/s eta 0:00:0000:0100:02
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.5.1)
Collecting matplotlib
  Downloading matplotlib-3.6.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 1.2 MB/s eta 0:00:0000:0100:01m
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 KB 760.4 kB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.17.3 in /usr/lib/python3/dist-packages (from scikit-learn) (1.21.5)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib) (0.11.0)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.1/296.1 KB 1.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3/dist-packages (from matplotlib) (4.29.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (22.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Installing collected packages: threadpoolctl, scipy, joblib, contourpy, scikit-learn, matplotlib
  Attempting uninstall: scipy
    Found existing installation: scipy 1.8.0
    Not uninstalling scipy at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'scipy'. No files were found to uninstall.
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.1
    Not uninstalling matplotlib at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'matplotlib'. No files were found to uninstall.
Successfully installed contourpy-1.0.6 joblib-1.2.0 matplotlib-3.6.2 scikit-learn-1.2.0 scipy-1.9.3 threadpoolctl-3.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [4]:
# sklearn basics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
# read data
test11 = pd.read_csv("https://gist.githubusercontent.com/Wizerlous/97826525a05111f3dc7629727c117802/raw/7ad3b8e90d9d55a94994faa48e50b50b14c89c7e/testfile.csv")
test11

,PROV_CODE,PROV_NAME,Years,ALL_EL,All_mortal_EL,Cardiovas_EL,Res_EL,Lung_EL,Den_Pop,GPP_PERCAP,Tem,Pm2.5,N,NE,M,E,W,S,region
0,10,BANGKOK,2012,5.067310e+09,2.945649e+09,7.576136e+08,4.440903e+08,9.199571e+08,3616.15,430017.48,28.806,26.776328,0,0,1,0,0,0,M
1,10,BANGKOK,2013,5.479635e+09,3.183978e+09,8.186236e+08,4.802630e+08,9.967704e+08,3624.24,460838.28,28.349,28.665552,0,0,1,0,0,0,M
2,10,BANGKOK,2014,4.125375e+09,2.398803e+09,6.171158e+08,3.615211e+08,7.479353e+08,3628.09,485784.91,28.787,25.470462,0,0,1,0,0,0,M
3,10,BANGKOK,2015,3.818239e+09,2.220773e+09,5.714355e+08,3.345897e+08,6.914401e+08,3630.71,511938.42,29.077,24.342081,0,0,1,0,0,0,M
4,10,BANGKOK,2016,4.315389e+09,2.509217e+09,6.455051e+08,3.781747e+08,7.824918e+08,3624.49,543199.32,28.959,25.601934,0,0,1,0,0,0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,96,NARATHIWAT,2014,2.031399e+07,1.183633e+07,3.050216e+06,1.779477e+06,3.647966e+06,172.80,55968.65,25.893,16.265809,0,0,0,0,0,1,S
535,96,NARATHIWAT,2015,2.848848e+07,1.659048e+07,4.273442e+06,2.495818e+06,5.128747e+06,174.64,53798.41,25.956,18.682346,0,0,0,0,0,1,S
536,96,NARATHIWAT,2016,2.215313e+07,1.291620e+07,3.330286e+06,1.940328e+06,3.966315e+06,176.11,58708.15,26.399,13.363510,0,0,0,0,0,1,S
537,96,NARATHIWAT,2017,8.999354e+06,5.247888e+06,1.353298e+06,7.881995e+05,1.609969e+06,177.58,56932.87,26.195,12.591984,0,0,0,0,0,1,S
538,96,NARATHIWAT,2018,2.830733e+07,1.650113e+07,4.253917e+06,2.479457e+06,5.072827e+06,178.97,62065.68,25.976,14.252539,0,0,0,0,0,1,S

In [6]:
# prepare data
X = test11.drop(["ALL_EL", "PROV_CODE","PROV_NAME","N","NE","M","E","W","S","Years","region"], axis=1)
y = test11["ALL_EL"]

# split data
X_train, X_test, y_train, y_test = train_test_split(
	X, y, test_size = 0.25, random_state = 42 #set.seed()
)

In [7]:
X_train.shape # ( row, column )

(404, 8)

In [8]:
X_train

,All_mortal_EL,Cardiovas_EL,Res_EL,Lung_EL,Den_Pop,GPP_PERCAP,Tem,Pm2.5
508,3.949183e+07,1.017640e+07,5.937733e+06,1.217648e+07,131.43,107955.02,27.097,16.597338
208,8.036253e+07,2.068819e+07,1.209947e+07,2.494041e+07,142.69,86142.69,25.157,21.786636
286,4.245472e+07,1.092943e+07,6.391975e+06,1.317524e+07,59.41,100708.56,23.577,21.754605
423,1.669375e+07,4.294797e+06,2.515759e+06,5.203674e+06,475.19,106551.76,29.213,25.264061
19,1.318920e+08,3.394702e+07,1.986344e+07,4.098754e+07,1941.94,187068.17,27.985,22.851731
...,...,...,...,...,...,...,...,...
71,5.473473e+08,1.408391e+08,8.246601e+07,1.704240e+08,311.08,418216.35,27.072,24.373950
106,7.091395e+07,1.824601e+07,1.068510e+07,2.208839e+07,95.56,372778.96,26.653,24.673956
270,1.395089e+08,3.591940e+07,2.100056e+07,4.325696e+07,78.68,124486.09,22.650,21.063395
435,4.874580e+07,1.254807e+07,7.339931e+06,1.513514e+07,80.82,150101.61,24.939,22.150380
102,2.652786e+08,6.828223e+07,3.994900e+07,8.241063e+07,134.47,430850.73,28.236,22.573793

In [9]:
# train model
model = LinearRegression()
model.fit(X_train, y_train)

# test model
p = model.predict(X_test)
print(p)

[3.48116548e+07 7.09892263e+08 1.53185754e+08 9.33099476e+07
 4.17822647e+07 9.27261247e+08 1.38275538e+07 3.60786504e+07
 6.93955285e+07 5.56990105e+07 4.10243639e+09 5.74363930e+07
 5.44586160e+08 4.68128606e+08 7.99875877e+07 1.13104872e+07
 9.49384026e+06 2.54068680e+08 3.02245604e+07 5.15782481e+07
 1.03915957e+07 3.33502321e+08 7.82135119e+07 7.90645526e+07
 2.44795127e+08 4.12537546e+09 3.37619734e+07 2.78873124e+07
 5.66137256e+08 4.82766920e+07 2.45480973e+07 1.93952610e+07
 3.54961586e+07 2.39937343e+08 4.94535357e+06 8.01403783e+06
 6.87477875e+07 6.87202862e+08 1.20867224e+08 6.61448730e+07
 7.53703684e+07 5.35761550e+07 3.24247447e+08 8.00782693e+07
 5.43657060e+07 5.59145935e+08 3.40187480e+08 1.24620336e+08
 1.06622558e+08 2.58438243e+08 7.52083817e+07 3.60840571e+07
 1.39870227e+08 5.48549818e+08 1.90277737e+07 1.22439396e+07
 5.89982595e+08 6.57041945e+07 1.32832245e+08 1.50310452e+08
 2.60919247e+07 1.04181357e+08 7.93636323e+08 2.03139919e+07
 4.43134165e+08 3.32375753e+07 6.45342234e+07 8.99935406e+06
 4.89981109e+07 2.29127142e+08 8.29517880e+08 1.74017928e+07
 6.18603454e+07 3.11166275e+07 1.30032885e+08 7.52988858e+07
 3.33371474e+08 2.55097947e+07 1.09210446e+08 6.48131329e+08
 5.52536441e+07 3.41419194e+08 8.07375212e+07 1.40484781e+08
 5.06731029e+09 5.93209341e+08 1.75617608e+07 3.66854158e+08
 5.08444607e+07 2.00193997e+07 4.19096571e+07 6.47005873e+07
 1.00513274e+08 8.53829477e+07 2.80661125e+08 5.22113631e+08
 9.18965613e+07 3.98140978e+08 5.50338517e+07 6.06195329e+07
 5.43512176e+07 6.78946471e+07 1.39703832e+08 3.09314053e+07
 2.02338649e+07 1.52361771e+07 1.10267243e+08 2.83073261e+07
 3.43011965e+07 1.24768695e+08 4.45223728e+07 3.36398930e+07
 5.11890831e+07 1.15692896e+08 3.19724568e+07 1.80247746e+08
 6.62987478e+07 2.84884835e+07 1.27559948e+08 6.16977114e+07
 2.41657482e+08 7.26621810e+07 9.31772361e+07 1.58364678e+08
 2.39288421e+08 2.06103180e+08 1.36706531e+08 1.30669710e+08
 3.21383829e+07 9.64310295e+07 2.99397513e+07 3.50914081e+07
 1.64107900e+08 4.33954618e+08 5.45618396e+07]

In [11]:
model.score(X_test, y_test) # R2

1.0